Create 2024-01-08
department-of-veterans-affairs/developer-portal-content pull request #105
Opened 2024-01-04 22:06 UTC by mashaeva-va

Release Note for CHAPI

2024-01-08 21:53 UTC, joeabraun requested changes
Made a couple of changes.

2024-01-08 21:53 UTC, joeabraun commented on content/health/clinical-fhir-api/release-notes/2024-01-08
> +• No changes are made to the existing general MedicationRequest calls, no unreleased medications are returned.
```suggestion
• No changes are made to the existing general MedicationRequest calls, and no unreleased medications are returned. 
```

2024-01-08 21:53 UTC, joeabraun commented on content/health/clinical-fhir-api/release-notes/2024-01-08
> +• When there is a search for a specific MedicationRequest using *identifier*, the view is changed to search for the medications only for that patient and include the unreleased medications.
```suggestion
• When a search request uses a patient identifier, a VistA medication order ID, and the VistA site number where the order was placed, results will only show that patient's medications, including their unreleased medications.
```

2024-01-08 21:56 UTC, joeabraun requested changes

2024-01-08 21:56 UTC, joeabraun commented on content/health/clinical-fhir-api/release-notes/2024-01-08
> +We have updated MedicationRequest resource to include unreleased medications data.
```suggestion
We have updated the MedicationRequest resource to include unreleased medications data.
```

2024-01-08 21:56 UTC, joeabraun approved these changes
UX approves!

2024-01-10 21:58 UTC, jlsexton submitted a review, later dismissed

2024-01-11 13:40 UTC, jlsexton approved these changes

2024-01-11 13:46 UTC, jlsexton approved these changes

2024-01-11 15:17 UTC, joeabraun approved these changes
UX approves.

2024-01-11 18:58 UTC, merged