Create 2024-02-13.md
department-of-veterans-affairs/developer-portal-content pull request #114
Opened 2024-02-13 21:49 UTC by camronmartinez

Release notes for the update to VSHE which  adds 2 restricted endpoints that will allow government agencies to search for Veterans using SSN

2024-02-14 20:21 UTC, joeabraun requested changes
Just added some small changes to reflect what is written in our currently published release notes.

2024-02-14 20:50 UTC, joeabraun requested changes
A couple small changes, and should be good to go.

2024-02-14 20:50 UTC, joeabraun commented on content/verification/veteran-verification/release-notes/2024-02-13.md
> +We've added two restricted access endpoints that allow government agencies to search for Veterans using social security numbers (SSN), enhancing accessibility while ensuring data privacy.
```suggestion
We've added two restricted access endpoints that allow government agencies to search for Veterans using social security numbers (SSNs), enhancing accessibility while ensuring data privacy.
```

2024-02-14 20:50 UTC, joeabraun commented on content/verification/veteran-verification/release-notes/2024-02-13.md
> +To learn more, see the [Veteran Service History and Eligibility v2 documentation](https://developer.va.gov/explore/api/veteran-service-history-and-eligibility/docs?version=current)
```suggestion
To learn more, review the [Veteran Service History and Eligibility v2 documentation](https://developer.va.gov/explore/api/veteran-service-history-and-eligibility/docs?version=current). 
```

2024-02-15 01:45 UTC, joeabraun approved these changes
Looks good to me. UX approves!

2024-02-15 14:42 UTC, melliroo commented on content/verification/veteran-verification/release-notes/2024-02-13.md
Confirmed w/ Lorri that "approved federal consumers" can replace "government agencies"

2024-02-15 18:00 UTC, camronmartinez commented on content/verification/veteran-verification/release-notes/2024-02-13.md
I've updated the wording to reflect "approved federal consumers"

2024-02-28 16:06 UTC, melliroo approved these changes

2024-02-28 16:14 UTC, merged