Create 2023-06-01
department-of-veterans-affairs/developer-portal-content pull request #73
Opened 2023-06-01 16:46 UTC by Mburnett-VA

Veteran Service History & Eligibility V2 Release Notes

2023-06-01 17:59 UTC, darduda requested changes
reviewed with some very minor changes. The only major changes would be to update the links showing in the OAuth and CCG part since they point to the claims API right now.

2023-06-02 13:15 UTC, Mburnett-VA commented on content/verification/veteran-verification/release-notes/2023-06-01
> +- Review the API documentation to learn more about the new version of this API.
Done

2023-06-02 14:48 UTC, joeabraun requested changes
Just need to change the URL links for Auth Code Flow and CCG, and then should be good to go.

2023-06-02 15:36 UTC, joeabraun requested changes

2023-06-02 15:36 UTC, joeabraun commented on content/verification/veteran-verification/release-notes/2023-06-01.md
> +- Review the [API documentation](https://developer.va.gov/explore/verification/docs/veteran_verification?version=current) to learn more about the new version of this API.
```suggestion
Review the [API documentation](https://developer.va.gov/explore/verification/docs/veteran_verification?version=current) to learn more about the new version of this API.
```

2023-06-02 15:37 UTC, joeabraun approved these changes
This looks good to me. UX approves!

2023-06-02 16:23 UTC, merged